apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XBackendTrafficPolicy
metadata:
  name: httpbin-retry-policy
  namespace: default
spec:
  retryConstraint:
    budget:
      interval: 10s
      percent: 20
    minRetryRate:
      count: 5
      interval: 10s
  targetRefs:
    - group: ''
      kind: Service
      name: httpbin
