apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: secure-backend-policy
  namespace: secure-app
spec:
  targetRefs:
    - group: ''
      kind: Service
      name: secure-backend
      sectionName: https
  validation:
    caCertificateRefs:
      - group: ''
        kind: ConfigMap
        name: backend-ca
    hostname: backend.secureapp.com
