apiVersion: v1
kind: Config
clusters:
  - name: cluster5
    cluster:
      server: https://cluster5.example.invalid
contexts:
  - name: cluster5
    context:
      cluster: cluster5
      user: cluster5-user
users:
  - name: cluster5-user
    user:
      token: ""
current-context: cluster5
