{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "headlamp.fullname" . }}
  namespace: {{ include "headlamp.namespace" . }}
  labels:
    {{- include "headlamp.labels" . | nindent 4 }}
spec:
  {{- $maxUnavailable := .Values.podDisruptionBudget.maxUnavailable }}
  {{- $minAvailable := .Values.podDisruptionBudget.minAvailable }}
  {{- if not (kindIs "invalid" $maxUnavailable) }}
  maxUnavailable: {{ $maxUnavailable }}
  {{- end }}
  {{- if and (not (kindIs "invalid" $minAvailable)) (or (kindIs "invalid" $maxUnavailable) (ne (toString $minAvailable) "0")) }}
  minAvailable: {{ $minAvailable }}
  {{- end }}
  {{- if (semverCompare ">= 1.27-0" .Capabilities.KubeVersion.Version) }}
  {{- if hasKey .Values.podDisruptionBudget "unhealthyPodEvictionPolicy" }}
  {{- with .Values.podDisruptionBudget.unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ . }}
  {{- end }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "headlamp.selectorLabels" . | nindent 6 }}
{{- end }}
