/*
 * Copyright 2025 The Kubernetes Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const VALID_COMMAND = /^[a-z0-9][a-z0-9._-]*$/i;
const MAX_COMMAND_LENGTH = 128;
const MAX_ARGUMENTS = 16;
const MAX_ARGUMENT_LENGTH = 256;
const MAX_SCOPES = 64;

/** A command and argument prefix declared by a plugin manifest. */
export interface PluginCommandScope {
  /** Executable name. */
  command: string;
  /** Required argument prefix. */
  args: string[];
}

/** A declared command scope paired with an opaque authorization token. */
export interface PluginCommandCapability extends PluginCommandScope {
  /** Opaque authorization token generated by the desktop main process. */
  capability: string;
}

/**
 * Checks whether an untrusted value is a supported command scope.
 *
 * @param scope - Value read from plugin package metadata.
 * @returns Whether the value is a valid command scope.
 */
function isValidScope(scope: unknown): scope is PluginCommandScope {
  if (typeof scope !== 'object' || scope === null) {
    return false;
  }
  const { command, args = [] } = scope as { command?: unknown; args?: unknown };
  return (
    typeof command === 'string' &&
    command.length <= MAX_COMMAND_LENGTH &&
    VALID_COMMAND.test(command) &&
    Array.isArray(args) &&
    args.length <= MAX_ARGUMENTS &&
    args.every(
      arg => typeof arg === 'string' && arg.length <= MAX_ARGUMENT_LENGTH && !arg.includes('\0')
    )
  );
}

/**
 * Reads validated command scopes from plugin package metadata.
 *
 * @param packageInfo - Untrusted plugin package metadata.
 * @returns Valid command scopes declared under `headlamp.runCommands`.
 */
export function getDeclaredCommandScopes(packageInfo: unknown): PluginCommandScope[] {
  if (typeof packageInfo !== 'object' || packageInfo === null) {
    return [];
  }
  const headlamp = (packageInfo as { headlamp?: unknown }).headlamp;
  if (typeof headlamp !== 'object' || headlamp === null) {
    return [];
  }
  const runCommands = (headlamp as { runCommands?: unknown }).runCommands;
  if (!Array.isArray(runCommands) || runCommands.length > MAX_SCOPES) {
    return [];
  }
  return runCommands.filter(isValidScope).map(scope => ({
    command: scope.command,
    args: scope.args ?? [],
  }));
}

/**
 * Finds the capability whose command and argument prefix match a request.
 *
 * @param capabilities - Capabilities issued for one plugin.
 * @param command - Requested executable name.
 * @param args - Requested command arguments.
 * @returns The matching opaque capability, or undefined when no scope matches.
 */
export function findCommandCapability(
  capabilities: PluginCommandCapability[],
  command: string,
  args: string[]
): string | undefined {
  for (let scopeIndex = 0; scopeIndex < capabilities.length; scopeIndex++) {
    const scope = capabilities[scopeIndex];
    if (scope.command !== command || scope.args.length > args.length) {
      continue;
    }

    let matches = true;
    for (let argumentIndex = 0; argumentIndex < scope.args.length; argumentIndex++) {
      if (scope.args[argumentIndex] !== args[argumentIndex]) {
        matches = false;
        break;
      }
    }
    if (matches) {
      return scope.capability;
    }
  }

  return undefined;
}
