name: Build App

on:
  pull_request:
    paths:
    - 'frontend/**'
    - 'Makefile'
    - '.github/**'
    - 'app/**'
    - 'backend/**'
  push:
    branches:
      - main
      - rc-*
      - testing-rc-*
    paths:
    - 'frontend/**'
    - Makefile
    - '.github/**'
    - 'app/**'
    - 'backend/**'

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '1.24.*'
    - name: Run tests
      run: npm run app:test
    - name: Run tsc type checker
      run: npm run app:tsc
    - name: App linux
      run: |
        npm run app:package:linux
  build-windows:
    runs-on: windows-2025
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '1.24.*'
    - name: Run tests
      run: npm run app:test
    - name: Run tsc type checker
      run: npm run app:tsc
    - name: App Windows
      run: npm run app:package:win
  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '1.24.*'
    - name: Run tests
      run: npm run app:test
    - name: Run tsc type checker
      run: npm run app:tsc
    - name: App Mac
      run: |
        npm run app:package:mac
