name: Template test Helm charts

on:
  pull_request:
    paths:
      - charts/**
      - '!charts/**/README.md'
      - Makefile
      - .github/workflows/helm-chart-template-test.yml
      - charts/headlamp/tests/**
  push:
    branches:
      - main
      - rc-*
      - testing-rc-*
    
permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.18.4
          
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.13' 

      - name: Run template testing script
        run: |
          export SHELL=/bin/bash
          make helm-template-test
