name: Release Status Check

on:
  schedule:
    # Run every night at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch:
    # Allow manual trigger

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check-release-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: tools/releaser/package-lock.json

      - name: Install releaser dependencies
        run: |
          cd tools/releaser
          npm install

      - name: Build releaser tool
        run: |
          cd tools/releaser
          npm run build

      - name: Run release status check
        id: check-status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd tools/releaser
          # Run the check command with JSON output
          if node dist/index.js check LATEST_VERSION --json > release-status.json 2>&1; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
          # Always output the result for debugging
          cat release-status.json

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_OUTPUT

      - name: Create release status page
        run: |
          cd tools/releaser
          mkdir -p status-page
          
          # Read the JSON result
          RESULT=$(cat release-status.json)
          
          # Create the HTML page
          cat > status-page/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Headlamp Release Status</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                      line-height: 1.6;
                      color: #333;
                      max-width: 1200px;
                      margin: 0 auto;
                      padding: 20px;
                      background-color: #f8f9fa;
                  }
                  .container {
                      background: white;
                      border-radius: 8px;
                      padding: 30px;
                      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  }
                  .header {
                      text-align: center;
                      margin-bottom: 30px;
                      border-bottom: 2px solid #e9ecef;
                      padding-bottom: 20px;
                  }
                  .status-badge {
                      display: inline-block;
                      padding: 8px 16px;
                      border-radius: 20px;
                      font-weight: bold;
                      text-transform: uppercase;
                      font-size: 0.8em;
                      letter-spacing: 0.5px;
                  }
                  .status-success {
                      background-color: #d4edda;
                      color: #155724;
                      border: 1px solid #c3e6cb;
                  }
                  .status-error {
                      background-color: #f8d7da;
                      color: #721c24;
                      border: 1px solid #f5c6cb;
                  }
                  .metadata {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                      gap: 20px;
                      margin-bottom: 30px;
                  }
                  .metadata-item {
                      background: #f8f9fa;
                      padding: 15px;
                      border-radius: 5px;
                      border-left: 4px solid #007bff;
                  }
                  .metadata-label {
                      font-weight: bold;
                      color: #495057;
                      margin-bottom: 5px;
                  }
                  .metadata-value {
                      color: #6c757d;
                  }
                  .artifacts-section {
                      margin-top: 30px;
                  }
                  .artifacts-grid {
                      display: grid;
                      grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
                      gap: 15px;
                      margin-top: 20px;
                  }
                  .artifact-item {
                      display: flex;
                      align-items: center;
                      padding: 10px;
                      border-radius: 5px;
                      border: 1px solid #dee2e6;
                  }
                  .artifact-found {
                      background-color: #d4edda;
                      border-color: #c3e6cb;
                  }
                  .artifact-missing {
                      background-color: #f8d7da;
                      border-color: #f5c6cb;
                  }
                  .artifact-icon {
                      margin-right: 10px;
                      font-size: 1.2em;
                  }
                  .error-section {
                      background-color: #f8d7da;
                      border: 1px solid #f5c6cb;
                      border-radius: 5px;
                      padding: 20px;
                      margin-top: 20px;
                  }
                  .footer {
                      text-align: center;
                      margin-top: 40px;
                      padding-top: 20px;
                      border-top: 1px solid #e9ecef;
                      color: #6c757d;
                      font-size: 0.9em;
                  }
                  .footer a {
                      color: #007bff;
                      text-decoration: none;
                  }
                  .footer a:hover {
                      text-decoration: underline;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <div class="header">
                      <h1>🚀 Headlamp Release Status</h1>
                      <div id="status-badge"></div>
                  </div>
                  
                  <div class="metadata">
                      <div class="metadata-item">
                          <div class="metadata-label">Version</div>
                          <div class="metadata-value" id="version"></div>
                      </div>
                      <div class="metadata-item">
                          <div class="metadata-label">Last Checked</div>
                          <div class="metadata-value" id="timestamp"></div>
                      </div>
                      <div class="metadata-item">
                          <div class="metadata-label">Release Found</div>
                          <div class="metadata-value" id="release-found"></div>
                      </div>
                      <div class="metadata-item">
                          <div class="metadata-label">All Artifacts Present</div>
                          <div class="metadata-value" id="artifacts-status"></div>
                      </div>
                  </div>

                  <div class="artifacts-section">
                      <h2>📦 Release Artifacts</h2>
                      <div class="artifacts-grid" id="artifacts-grid"></div>
                  </div>

                  <div id="error-section" class="error-section" style="display: none;">
                      <h3>❌ Error Details</h3>
                      <p id="error-message"></p>
                  </div>

                  <div class="footer">
                      <p>Generated automatically by <a href="https://github.com/kubernetes-sigs/headlamp/actions">GitHub Actions</a></p>
                      <p>🔄 This page is updated nightly at 2:00 AM UTC</p>
                  </div>
              </div>

              <script>
                  // Embed the JSON data
                  const statusData = REPLACE_WITH_JSON_DATA;
                  
                  function updatePage() {
                      // Update status badge
                      const statusBadge = document.getElementById('status-badge');
                      if (statusData.success) {
                          statusBadge.textContent = '✅ Ready to Publish';
                          statusBadge.className = 'status-badge status-success';
                      } else {
                          statusBadge.textContent = '❌ Not Ready';
                          statusBadge.className = 'status-badge status-error';
                      }

                      // Update metadata
                      document.getElementById('version').textContent = statusData.version;
                      document.getElementById('timestamp').textContent = new Date(statusData.timestamp).toLocaleString();
                      document.getElementById('release-found').textContent = statusData.releaseFound ? '✅ Yes' : '❌ No';
                      document.getElementById('artifacts-status').textContent = statusData.allArtifactsPresent ? '✅ Yes' : '❌ No';

                      // Update artifacts grid
                      const artifactsGrid = document.getElementById('artifacts-grid');
                      artifactsGrid.innerHTML = '';
                      
                      Object.entries(statusData.foundAssets).forEach(([asset, found]) => {
                          const artifactItem = document.createElement('div');
                          artifactItem.className = `artifact-item ${found ? 'artifact-found' : 'artifact-missing'}`;
                          artifactItem.innerHTML = `
                              <span class="artifact-icon">${found ? '✅' : '❌'}</span>
                              <span>${asset}</span>
                          `;
                          artifactsGrid.appendChild(artifactItem);
                      });

                      // Show error section if there's an error
                      if (statusData.error) {
                          document.getElementById('error-section').style.display = 'block';
                          document.getElementById('error-message').textContent = statusData.error;
                      }
                  }

                  // Initialize the page
                  updatePage();
              </script>
          </body>
          </html>
          EOF
          
          # Replace the placeholder with actual JSON data
          # Escape the JSON properly for JavaScript
          ESCAPED_JSON=$(echo "$RESULT" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | tr -d '\n' | tr -d '\r')
          sed -i "s/REPLACE_WITH_JSON_DATA/$ESCAPED_JSON/g" status-page/index.html

      - name: Setup Pages
        if: steps.check-status.outputs.success == 'true' || steps.check-status.outputs.success == 'false'
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479e4c2a6e2884e4f8 # v5.0.0

      - name: Upload Pages artifact
        if: steps.check-status.outputs.success == 'true' || steps.check-status.outputs.success == 'false'
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: tools/releaser/status-page

  deploy:
    if: always() && needs.check-release-status.result != 'failure'
    needs: check-release-status
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5